name: Main Build
on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.TOKENGH }}
          registry: ghcr.io
      - name: Build Python_Bot
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/ddoser11/history_bot:latest
            ghcr.io/ddoser11/history_bot:${{ github.ref_name }}
          build-args: GITHUB_TOKEN=${{ secrets.TOKENGH }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.TOKENGH }}
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd history_bot
            docker-compose pull
            docker-compose up -d
